jitsi/jicoco

- src/main/java/org/jitsi/rest/MuxServerConnector.java
ice4j pom file excludes ```**/jdk8/**``` from compilation, so this import fails
Signed-off-by: Etienne CHAMPETIER <champetier.etienne@gmail.com>
> Don't import org.ice4j.socket.jdk8 (fix compilation)

- src/main/java/org/jitsi/xmpp/component/ComponentBase.java
This was spamming log file with
"GRAVE: Ping timeout for ID: ..."
Openfire drop ping with missing 'from'
Fixes jitsi/jitsi-videobridge#93
> Add from to ping request

- src/main/java/org/jitsi/version/AbstractVersionActivator.java
- src/main/java/org/jitsi/version/CurrentVersion.java
- src/main/java/org/jitsi/version/VersionImpl.java
VersionServiceImpl has been moved to Jicoco, so that it can be reused in other components. They have to provide VersionServiceActivator and CurrentVersion interface implementation. The method for injecting version remains the same(done in build.xml of the component).
See https://github.com/jitsi/jitsi-videobridge/compare/version_impl?expand=1 for usage example.
> Moves VersionService implementation from the JVB.

- src/main/java/org/jitsi/rest/AbstractJettyBundleActivator.java
- src/main/java/org/jitsi/rest/MuxServerConnector.java
At times I need to enable debug logging in Jetty for debugging purposes. Because we utilize Logger throughout our projects, I know how to enable debug logging there without looking at documentation. However, I don't remember how to enable debug logging in Jetty without going back to its documentation. That's why I hooked up Jetty's logging configuration to Logger.
> Jetty logging configuration through Logger

- src/main/java/org/jitsi/xmpp/component/ComponentBase.java
This PR reduces the size of XMPP component's packet processor pool to 1 in order to avoid out of order processing(in parallel). An error message will be logged if the time limit is exceeded(100 ms by default).
> Process XMPP packets in order

- src/main/java/org/jitsi/rest/AbstractJettyBundleActivator.java
Makes the config fields public so they can be used if needed from
extenders and other code.
> Updates config static fields to be public.

- src/main/java/org/jitsi/eventadmin/EventAdminImpl.java
The presence of non-demon thread from this pool prevents video bridge process from exist when shutdown is requested and all conferences completed.
> Shutdown thread pool when EventAdminImpl bundle is stopped.

- pom.xml
- src/main/java/org/jitsi/osgi/OsgiServiceProvider.java
- src/main/java/org/jitsi/osgi/VersionServiceProvider.java
- src/main/java/org/jitsi/rest/Version.java
- src/test/java/org/jitsi/rest/VersionTest.java
a rest resource under /about/version which polls any found
VersionService for version information.
this is the style the bridge uses and what i'm moving jicofo to, so moved this code out of the bridge and into jicoco for reuse.
> generic version rest endpoint

- jicoco-kotlin/src/main/kotlin/org/jitsi/config/ConfigExtensions.kt
- jicoco-kotlin/src/main/kotlin/org/jitsi/config/JitsiConfig.kt
- jicoco-kotlin/src/main/kotlin/org/jitsi/config/LegacyConfigFileLoader.kt
- jicoco-kotlin/src/main/kotlin/org/jitsi/config/TypesafeConfigSource.kt
@bgrozev I did this using the legacy field `ConfigUtils.PASSWORD_SYS_PROPS`, but the more I think about it, the more I think we should have a property in the config itself which defines the sensitive properties.  Some advantages of this approach:
1) We can have different sensitive fields per config
2) We don't have to worry about races to set the static `ConfigUtils.PASSWORD_SYS_PROPS` field in time before we load the config.
Let me know what you think.
> Mask sensitive fields when dumping config output

- jicoco/src/main/java/org/jitsi/xmpp/mucclient/MucClient.java
stopped.
This fixes a problem where due to the timings and the origin of the
network problem while trying to reconnect a closing stream tag was
received from server (detected that client is offline) just after a
period of network disconnection and after it resumed whic closes the
xmpp connection and stops trying to reconnect.
JVB 2020-06-18 04:03:07.303 WARNING: [11052] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener: Connection XMPPTCPConnection[jvb@auth.jvb.example.com/cnA7VGg-] (0) closed with error
java.net.SocketException: Connection reset
at java.net.SocketInputStream.read(SocketInputStream.java:210)
at java.net.SocketInputStream.read(SocketInputStream.java:141)
at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
at …
> fix: Retries connection on connection closed till the muc client is

- jicoco/src/main/java/org/jitsi/xmpp/mucclient/MucClient.java
There is a case on prosody restart where we can get in an endless loop
trying to login, when we are already logged in.
Getting:
SEVERE: [23] RetryStrategy$TaskRunner.run#198: org.jivesoftware.smack.SmackException$AlreadyLoggedInException: Client is already logged in
```
2020-07-09 12:16:01.455 INFO: [31] [hostname=localhost id=shard] MucClient$1.connected#268: Connected.
2020-07-09 12:16:01.652 INFO: [31] [hostname=localhost id=shard] MucClient$MucWrapper.join#777: Joined MUC: jvbbrewery@internal.auth.jitsi.example.com
2020-07-09 12:16:01.696 WARNING: [40] org.jivesoftware.smack.AbstractXMPPConnection.callConnectionClosedOnErrorListener: Connection XMPPTCPConnection[jvb@auth.jitsi.example.com/a126a69d-984d-4b4c-a37e-d08041232e73] (0) closed with error
java.io.EOFException: input contained …
```
> fix: Retry login if already logged in.

- jicoco-config/pom.xml
- jicoco-config/src/main/kotlin/org/jitsi/config/ConfigSourceWrapper.kt
- jicoco-config/src/main/kotlin/org/jitsi/config/JitsiConfig.kt
- jicoco-test-kotlin/pom.xml
- jicoco-test-kotlin/src/main/kotlin/org/jitsi/config/ConfigTestHelpers.kt
- jicoco-test-kotlin/src/main/kotlin/org/jitsi/config/TestReadOnlyConfigurationService.kt
This PR changes the way we hold on to `ConfigSource`s in `JitsiConfig`.  Before, we held a source directly in a `var` and, when testing, would merely re-assign the var.  This doesn't work when a property gets initialized before we have a chance to swap in the config we want (which can often be the case when config classes are held as static members).  This PR changes `JitsiConfig` to use a wrapper around a source, such that a 'stale' `ConfigSource` reference won't cause an issue when testing.
It also defines a set of helpers to create and re-assign the underlying configuration sources for legacy and new config for the purposes of testing.
> Config source wrapper

- jicoco-test-kotlin/pom.xml
I think I originally put this here as a common place to bring in the test lib dependency, but in practice I'm not sure that makes sense--a breaking change would then require updating everything which depended on it at once and it's just not that critical that all repos are on the same test version.
> remove kotlintest dep

- jicoco/pom.xml
- jicoco/src/main/java/org/jitsi/rest/AbstractJettyBundleActivator.java
- jicoco/src/main/kotlin/org/jitsi/rest/JettyBundleActivatorConfig.kt
A couple notes on this:
1. Technically this PR contains a breaking change: previously, if the `keyStorePath` value was not an absolute path, `AbstractJettyBundleActivator` would attempt to resolve it relative to the user's home directory and, if the user's home directory couldn't be determined, the current directory.  I removed that logic and it's now required to be an absolute path (**even for the legacy config file**).  I didn't replicate the old behavior because it was leveraging some features of the legacy `ConfigurationService`.  I did check our infra code and saw that we always set it as an absolute path.
1. Jicoco defined defaults for some of these values before and I preserved those, but I'm not sure it makes sense for them to stay there (as opposed to living in `reference.conf`)
> Port AbstractJettyBundleActivator to new config

- jicoco-config/src/main/kotlin/org/jitsi/config/TypesafeConfigSource.kt
- jicoco-config/src/test/kotlin/org/jitsi/config/TypesafeConfigSourceTest.kt
I looked at adding support in `TypesafeConfigSource` for adding 'custom' getters dynamically to address both this case (add common support for a new type) and allowing repos to add support for their own custom types, but ultimately I thought it may not be good to have conversion logic separate from the definition of the property, as it felt a bit 'opaque', so I went this route and explicitly added support for this new type and the repos can continue to do the conversion logic in place (or in helper functions) using `convertFrom`.
> Add support for 'Pattern'

- jicoco/src/main/java/org/jitsi/xmpp/mucclient/MucClient.java
We are seeing issues where jibri stays connected to the XMPP server (the socket is seen in the OS), but never send pings but the XMPP server had timed out the connection and that jibri is not in the brewery room (no socket connection on the XMPP server-side). And jibri in the meantime is reporting healthy through the HTTP api.
The reconnection manager is working on connection failed events, apparently, this had not been triggered.
The ping manager stops sending pings when a ping fails, when we disconnect and authenticate the same connection the ping manager will continue working.
> feat: Handles two ping failures and trigger a reconnect.

- jicoco/src/main/java/org/jitsi/xmpp/mucclient/MucClient.java
This is a workaround for a failure to re-login we observe, in which
Smack's state indicates that the XMPPConnection is connected, but is
unable to login because the server did not indicate SASL support.
> Fix failures to re-login.

- jicoco-config/src/main/kotlin/org/jitsi/config/JitsiConfig.kt
https://github.com/jitsi/jicoco/pull/118 Fixed an issue with overriding defaults in a lib, but it also moved away from calling `ConfigFactory#load` which called `Config#resolve` to resolve substitutions.  Since we're not calling that anymore, we need to call `resolve` explicitly.
> make a call to resolve when loading config

- jicoco/pom.xml
- jicoco/src/main/kotlin/org/jitsi/rest/JettyHelpers.kt
This will allow, in addition to creating an SSH tunnel, the jvb dashboard to connect to the jvb REST api to render the stats
> add helper to enable cors

- jicoco/bnd.bnd
Nothing uses jicoco as a bundle
> fix: Do not export all org.jitsi.* packages (includes classes from jitsi-utils).

- jicoco/src/main/kotlin/org/jitsi/rest/JettyBundleActivatorConfig.kt
- jicoco/src/main/kotlin/org/jitsi/rest/JettyHelpers.kt
As I explained [here](https://community.jitsi.org/t/how-to-hide-jetty-version-from-responses/97677), I'd like to be able to hide the Jetty version from error responses. 
This PR adds this option to Jicoco.
I've tried it with [f8e9405198e0c20e8b0c82af7a65108809fef78e](https://github.com/jitsi/jicoco/commit/f8e9405198e0c20e8b0c82af7a65108809fef78e) and a [JVB 5390](https://github.com/jitsi/jitsi-videobridge/releases/tag/stable%2Fjitsi-meet_5390).
I didn't see Jetty version in responses as I expected when I set `org.jitsi.videobridge.rest.jetty.sendServerVersion=false` in JVB params.
> Added option to control sendServerVersion parameter of Jetty

- jicoco/src/main/java/org/jitsi/xmpp/mucclient/MucClientManager.java
This will enable `/colibri/muc-client/list` on jitsi-videobridge.
Ref: https://community.jitsi.org/t/list-added-muc-clients-on-videobridge/100268/6?u=shawn
> Add getMucClientIds to MucClientManager

- jicoco/src/main/java/org/jitsi/xmpp/mucclient/ConnectionStateListener.java
- jicoco/src/main/java/org/jitsi/xmpp/mucclient/MucClient.java
- jicoco/src/main/java/org/jitsi/xmpp/mucclient/MucClientManager.java
- fix: Increase the half-open check interval.
- hack: Try to unblock SmackReactor before triggering a re-connect.
- feat: Add an interface to expose connection state changes.
- log: Log the first time a half-open connection is detected.
- squash: Make the interface public.
> Reconnection fixes

- jicoco-test-kotlin/src/main/kotlin/org/jitsi/test/concurrent/FakeScheduledExecutorService.kt
- jicoco-test-kotlin/src/test/kotlin/org/jitsi/test/concurrent/FakeScheduledExecutorServiceTest.kt
- jicoco/src/test/java/org/jitsi/retry/RetryStrategyTest.java
This lets us instantiate it without using mock/spy, which is substantially faster and uses less heap.
> Implement all stub methods for FakeScheduledExecutorService.

- jicoco-metrics/src/main/kotlin/org/jitsi/metrics/BooleanMetric.kt
- jicoco-metrics/src/main/kotlin/org/jitsi/metrics/CounterMetric.kt
- jicoco-metrics/src/main/kotlin/org/jitsi/metrics/DoubleGaugeMetric.kt
- jicoco-metrics/src/main/kotlin/org/jitsi/metrics/InfoMetric.kt
- jicoco-metrics/src/main/kotlin/org/jitsi/metrics/LongGaugeMetric.kt
- jicoco-metrics/src/main/kotlin/org/jitsi/metrics/Metric.kt
- jicoco-metrics/src/main/kotlin/org/jitsi/metrics/MetricsContainer.kt
- jicoco-metrics/src/test/kotlin/org/jitsi/metrics/MetricsContainerTest.kt
Adds a `resetAll()` method to `MetricsContainer` which resets all of its `Metrics` to their respective initial values.
> feat: Add resetAll() to MetricsContainer for testing.

- jicoco-metrics/src/main/java/org/jitsi/rest/prometheus/Prometheus.java
- jicoco-metrics/src/main/kotlin/org/jitsi/metrics/MetricsContainer.kt
- jicoco-metrics/src/test/kotlin/org/jitsi/metrics/MetricsContainerTest.kt
As discussed in [this jitsi-videobridge PR](https://github.com/jitsi/jitsi-videobridge/pull/1942).
> Append missing _total suffix when registering Counter metrics.

- jicoco/src/main/java/org/jitsi/xmpp/mucclient/MucClient.java
Attempts to address jitsi/jitsi-videobridge#2052 by not sending presence
unavailable when disconnecting due to a connection failure. If the TCP
connection is alive then the server will notice that it's closed. If it
isn't alive then it won't matter anyway.
> fix: Do not send presence unavailable after a failure.

- jicoco/src/main/java/org/jitsi/xmpp/mucclient/MucClient.java
- pom.xml
In case prosody is not fully up we can receive StreamErrorException: invalid-namespace and at the same time we are connected which will cause reconnection to stop.
> fix(reconnect): Handle - reconnect too quickly and fail.

- jicoco-metrics/src/main/kotlin/org/jitsi/metrics/BooleanMetric.kt
- jicoco-metrics/src/main/kotlin/org/jitsi/metrics/CounterMetric.kt
- jicoco-metrics/src/main/kotlin/org/jitsi/metrics/DoubleGaugeMetric.kt
- jicoco-metrics/src/main/kotlin/org/jitsi/metrics/InfoMetric.kt
- jicoco-metrics/src/main/kotlin/org/jitsi/metrics/LongGaugeMetric.kt
- jicoco-metrics/src/main/kotlin/org/jitsi/metrics/Metric.kt
- jicoco-metrics/src/main/kotlin/org/jitsi/metrics/MetricsContainer.kt
- jicoco-metrics/src/test/kotlin/org/jitsi/metrics/MetricTest.kt
- **feat: Support labels for CounterMetric.**
- **feat: Add labels support to DoubleGaugeMetric.**
- **feat: Add labels support to LongGaugeMetric.**
- **feat: Add labels support to BooleanMetric.**
- **feat: Add labels support to InfoMetric.**
> Support metric labels (prometheus).
