jitsi/jicoco

src/main/java/org/jitsi/eventadmin/Activator.java, src/main/java/org/jitsi/eventadmin/Event.java, src/main/java/org/jitsi/eventadmin/EventAdminImpl.java
Adds EventHandler service instance caching and event topic matching.
=> Extended EventAdmin implementation.

src/main/java/org/jitsi/xmpp/util/IQUtils.java
The problem was that we were not expecting IQ class to be returned by ProviderManager, but it turned out that Smack does it this way as well.
=> Fixes parsing the of Version IQ

src/main/java/org/jitsi/assertions/Assert.java
Got bored of writing:
<code>
if (var == null) { throw new NullPointerException(errorMsg); }
</code>
=> Adds Assert class.

src/main/java/org/jitsi/eventadmin/EventAdmin.java, src/main/java/org/jitsi/eventadmin/EventAdminImpl.java
postEvent can be used to propagate events asynchronously
=> Adds EventAdmin.postEvent method for async events

src/main/java/org/jitsi/eventadmin/EventAdminImpl.java
This PR gets rid of synchronized from sendEvent and postEvent methods.
=> Get rid event sync

src/main/java/org/jitsi/xmpp/component/ComponentBase.java
Reverts the changes from the previous PR about using 1 packet processing thread. Modifies the time measurement logic to work with multiple threads.
=> Use 17 threads to process XMPP packets

.gitignore, src/main/java/org/jitsi/assertions/Assert.java
As it is the same as Objects.requireNonNull().
=> Minor clean-up: removes Assert.notNull

pom.xml, src/main/java/org/jitsi/meet/ComponentMain.java, src/main/java/org/jitsi/meet/OSGi.java, src/main/java/org/jitsi/meet/OSGiBundleConfig.java, src/main/java/org/jitsi/meet/OSGiClassLoader.java
adds possibility to load jar files with bundles from ConfigurationService.PNAME_SC_HOME_DIR_LOCATION / ConfigurationService.PNAME_SC_HOME_DIR_NAME / 
bundles/
directory
=> adds possibility to load jar with bundles form BUNDLES_JARS_PATH directory

src/main/java/org/jitsi/xmpp/mucclient/MucClient.java
Depends on https://github.com/jitsi/jicofo/pull/385.
=> Checks whether the incoming iq is from the control room we have.

pom.xml, src/main/java/org/jitsi/meet/ComponentMain.java, src/main/java/org/jitsi/meet/OSGiBundleConfig.java
depends on https://github.com/jitsi/jitsi-utils/pull/30
=> set password masks via configutils, gets rid of need for libjitsi dep

.gitignore, jicoco/src/main/java/org/jitsi/xmpp/mucclient/MucClient.java, jicoco/src/main/java/org/jitsi/xmpp/mucclient/MucClientManager.java
and lowers the level of the "setting extension" log.
=> Migrates MucClient to the new logger

jicoco/pom.xml
Looks like it improves JDK11 compatibility.
=> Bump Jersey version.

jicoco/src/main/kotlin/org/jitsi/rest/JettyBundleActivatorConfig.kt
These keys were mis-copied in https://github.com/jitsi/jicoco/pull/99
=> fix jetty keys

jicoco-config/pom.xml
=> Use typesafe config 1.4.1.

jicoco/src/main/kotlin/org/jitsi/rest/JettyHelpers.kt, pom.xml
Note: requires jitsi/jitsi-utils#74
=> Move JettyHelpers from jvb to jicoco.

jicoco-metrics/checkstyle.xml, jicoco-metrics/pom.xml, jicoco-metrics/src/main/kotlin/org/jitsi/metrics/BooleanMetric.kt, jicoco-metrics/src/main/kotlin/org/jitsi/metrics/CounterMetric.kt, jicoco-metrics/src/main/kotlin/org/jitsi/metrics/DoubleGaugeMetric.kt, jicoco-metrics/src/main/kotlin/org/jitsi/metrics/InfoMetric.kt, jicoco-metrics/src/main/kotlin/org/jitsi/metrics/LongGaugeMetric.kt, jicoco-metrics/src/main/kotlin/org/jitsi/metrics/Metric.kt, jicoco-metrics/src/main/kotlin/org/jitsi/metrics/MetricsContainer.kt, jicoco-metrics/src/test/kotlin/org/jitsi/metrics/MetricTest.kt, jicoco-metrics/src/test/kotlin/org/jitsi/metrics/MetricsContainerTest.kt, pom.xml
This commit relates to PR #1915 in jitsi-videobridge.
The metrics package (the core of the project) is moving to jicoco.
See: https://github.com/jitsi/jitsi-videobridge/pull/1915/
=> Rework metrics system for Prometheus (moved from jvb).

jicoco-metrics/pom.xml, jicoco-metrics/src/main/java/org/jitsi/rest/prometheus/Prometheus.java, jicoco-metrics/src/test/kotlin/org/jitsi/rest/prometheus/PrometheusTest.kt
* Add Prometheus REST endpoint.
* Add tests.
* Update pom.xml.
This commit relates to PR #1915 in jitsi-videobridge.
Signed-off-by: Alexandre Fonseca <4717855+alexcsf@users.noreply.github.com>
=> Add Prometheus REST endpoint (moved from JVB).

.editorconfig, jicoco-metrics/pom.xml, jicoco-metrics/src/main/kotlin/org/jitsi/metrics/MetricsContainer.kt, jicoco-test-kotlin/pom.xml, jicoco/pom.xml, pom.xml
Apply ktlint fixes from ktlint 0.50.0.
=> Update Kotlin to 1.9.10, and related Maven packages.

jicoco-config/pom.xml, jicoco-metrics/pom.xml, jicoco-test-kotlin/pom.xml, pom.xml
- fix: Fixes building jicoco-metrics.
- fix: Fixes generating docs for jicoco.
=> jicoco module to maven central

pom.xml
- Revert "fix: Drops dokka dependency."
- fix: Updates phases for dokka plugin.
=> feat: Updates javadoc preparation for maven central.
